### ISSUE TITLE
有关使用百度地图源的第三方客户端

### ISSUE THREAD

**Issue by inused** [neoFelhz/neohosts#10]
* 有关此 `issue` 的目的：(请将 `[ ]` 中的空格替换为 `x` 以勾选)
- [x] 反馈误杀/申请解封（影响到关键服务的正常运行）
- [ ] 申请审查（申请维护者对一个含广告的网站进行分析和数据完善）
- [ ] 提交域名/数据（发现一个广告域名，想提交给 neoHosts）
- [ ] 申请技术支持
- [ ] 其它问题

---

* 您要反馈的问题：
api.map.baidu.com 屏蔽该域名会导致使用百度地图源的第三方地图软件无法显示地图(百度地图官方客户端有没有影响不清楚)
loc.map.baidu.com 和 ofloc.map.baidu.com 可能是和实时路况还有离线地图之类的有关，不是很确定
现在的情况是，无法显示地图，无法下载离线地图，不显示实时路况
---
* 图
安卓地图软件 Bmap ，来自酷安
正常情况显示
![屏蔽前](https://i.loli.net/2017/11/07/5a01488cc1a11.jpg)
使用host之后
![屏蔽后](https://i.loli.net/2017/11/07/5a01488c9c723.jpg)
抓包抓到这几个
![抓包](https://i.loli.net/2017/11/07/5a01488c04601.png)
另外，使用host之后会一直请求 ipv6 地址，用的 adaway，设置中没有开启ipv6 . host里面4和6的规则都在，宽带没有ipv6，是ipv6优先级比ipv4高吗？
![api](https://i.loli.net/2017/11/07/5a01488ce28d5.jpg)
---
使用 fiddler 抓包
[抓包结果](https://github.com/neko-dev/neohosts/files/1448872/fiddler.zip)

**Comment by neoFelhz** [comment]
收到。
这部分域名是为了阻止百度全家桶时刻监听和窃取位置隐私的。
现在这部分域名会从基础数据中移除，转移至附加数据中。

**Comment by neoFelhz** [comment]
数据已经调整，请在五分钟后更新基础 Hosts，并使用开关飞行模式、重启等方式使 Hosts 的改动生效。
