### ISSUE TITLE
Full Hosts 额外屏蔽的内容能不能单独做一个过滤列表

### ISSUE THREAD

**Issue by ihuaer** [neoFelhz/neohosts#102]
* 您要反馈的问题：
Full Hosts 额外屏蔽的内容能不能单独做一个过滤列表
仅仅想过滤这些网站

**Comment by ihuaer** [comment]
done

**Comment by yyy33** [comment]
😊


---原始邮件---
发件人: &quot;larryzhu&quot;<notifications@github.com&gt;
发送时间: 2021年1月25日(周一) 下午2:53
收件人: &quot;neoFelhz/neohosts&quot;<neohosts@noreply.github.com&gt;;
抄送: &quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题: Re: [neoFelhz/neohosts] Full Hosts 额外屏蔽的内容能不能单独做一个过滤列表 (#102)




 
done
 
&mdash;
