### ISSUE TITLE
完整版屏蔽部分域名导致新浪微博网页版无法正常使用

### ISSUE THREAD

**Issue by iKirby** [neoFelhz/neohosts#11]
* 有关此 `issue` 的目的：(请将 `[ ]` 中的空格替换为 `x` 以勾选)
- [x] 反馈误杀/申请解封（影响到关键服务的正常运行）
- [ ] 申请审查（申请维护者对一个含广告的网站进行分析和数据完善）
- [ ] 提交域名/数据（发现一个广告域名，想提交给 neoHosts）
- [ ] 申请技术支持
- [ ] 其它问题

---

* 您要反馈的问题：

在完整数据中

```
js.t.sinajs.cn
js1.t.sinajs.cn
js2.t.sinajs.cn
```

三个域名的屏蔽导致新浪微博网页版工作不正常（查看评论、点赞等按钮无法点击等）

**Comment by neoFelhz** [comment]
我会去检查一下。

**Comment by neoFelhz** [comment]
经检查，这三个域名确实是误杀，将会去除

**Comment by iKirby** [comment]
新版本中已经没有这个问题了，多谢！
