### ISSUE TITLE
Google AD相关

### ISSUE THREAD

**Issue by lrinQVQ** [neoFelhz/neohosts#12]
* 有关此 `issue` 的目的：(请将 `[ ]` 中的空格替换为 `x` 以勾选)
- [ ] 反馈误杀/申请解封（影响到关键服务的正常运行）
- [ ] 申请审查（申请维护者对一个含广告的网站进行分析和数据完善）
- [ ] 提交域名/数据（发现一个广告域名，想提交给 neoHosts）
- [ ] 申请技术支持
- [x] 其它问题

---

* 您要反馈的问题：
貌似在pagead[1-5].googlesyndication.com中只有pagead2.googlesyndication.com是有效的域名0.0,为了文件的整洁性推荐移除1,3,4,5
避免issues长度太长详见dig日志
[dig.log](https://github.com/neko-dev/neohosts/files/1478568/dig.log)

以及发现了重复域名googleads.g.doubleclick.net
https://github.com/neko-dev/neohosts/blob/261cc617b39e6eb1fc1a0e885b02649c6d73660f/_data/basic/g-ad.txt#L6

https://github.com/neko-dev/neohosts/blob/261cc617b39e6eb1fc1a0e885b02649c6d73660f/_data/basic/g-ad.txt#L20

**Comment by lrinQVQ** [comment]
以及第二个问题
Youtube开头的视频广告请求域名:ade.googlesyndication.com
测试视频:https://www.youtube.com/watch?v=ydxG67SsVPQ

**Comment by neoFelhz** [comment]
经检查：`pagead1.googlesyndication.com` `pagead3.googlesyndication.com` `pagead4.googlesyndication.com` `pagead5.googlesyndication.com` 确实已经停止解析，将会去除。

在测试视频的链接中，未检测到 `ade.googlesyndication.com`，暂时不予添加，留待以后检测。

**Comment by lrinQVQ** [comment]
咩可能是地区问题 我稍后截个图

**Comment by lrinQVQ** [comment]
暂时又无法复现我先Close
