### ISSUE TITLE
新浪博客功能不正常

### ISSUE THREAD

**Issue by iKirby** [neoFelhz/neohosts#14]
* 有关此 `issue` 的目的：(请将 `[ ]` 中的空格替换为 `x` 以勾选)
- [x] 反馈误杀/申请解封（影响到关键服务的正常运行）
- [ ] 申请审查（申请维护者对一个含广告的网站进行分析和数据完善）
- [ ] 提交域名/数据（发现一个广告域名，想提交给 neoHosts）
- [ ] 申请技术支持
- [ ] 其它问题

---

* 您要反馈的问题：
`simg.sinajs.cn` 被屏蔽导致新浪博客 CSS 等无法加载

**Comment by neoFelhz** [comment]
![screenshot_20171120-194403](https://user-images.githubusercontent.com/19367350/33016908-3cee1fd2-ce2b-11e7-8458-9b61339db961.png)
确认为误杀，将会移除。
