### ISSUE TITLE
完整屏蔽数据导致网页版 QQ 空间无法正常工作

### ISSUE THREAD

**Issue by iKirby** [neoFelhz/neohosts#15]
* 有关此 `issue` 的目的：(请将 `[ ]` 中的空格替换为 `x` 以勾选)
- [x] 反馈误杀/申请解封（影响到关键服务的正常运行）
- [ ] 申请审查（申请维护者对一个含广告的网站进行分析和数据完善）
- [ ] 提交域名/数据（发现一个广告域名，想提交给 neoHosts）
- [ ] 申请技术支持
- [ ] 其它问题

---

* 您要反馈的问题：

以下域名屏蔽导致网页版 QQ 空间不正常
```
qzs.qq.com
i.gtimg.cn
```

**Comment by neoFelhz** [comment]
是网页版 QQ 空间还是 QQ 客户端呢？

**Comment by BROBIRD** [comment]
这两个域名我在网页版上看到过

**Comment by iKirby** [comment]
@neoFelhz 网页版 QQ 空间，对客户端有没有影响不清楚。

**Comment by neoFelhz** [comment]
确认 `i.gtimg.cn` 是 Qzone 网页版的 CDN 域名、`qzs.qq.com` 是 Qzone CDN 域名 `qzonestyle.gtimg.cn` 的备份域名。这两个域名都将会从 neoHosts 移除。
