### ISSUE TITLE
贴吧图片误杀

### ISSUE THREAD

**Issue by ShadowLyin** [neoFelhz/neohosts#17]
* 有关此 `issue` 的目的：(请将 `[ ]` 中的空格替换为 `x` 以勾选)
- [x] 反馈误杀/申请解封（影响到关键服务的正常运行）
- [ ] 申请审查（申请维护者对一个含广告的网站进行分析和数据完善）
- [ ] 提交域名/数据（发现一个广告域名，想提交给 neoHosts）
- [ ] 申请技术支持
- [ ] 其它问题

---

* 您要反馈的问题：
使用 puretie 第三方贴吧客户端时无法显示图片。
经排查为`c.hiphotos.baidu.com`误杀。

**Comment by neoFelhz** [comment]
请提供抓包记录

**Comment by ShadowLyin** [comment]
[tieba.zip](https://github.com/neko-dev/neohosts/files/1564481/tieba.zip)
本人不大了解这块知识，如提供错误的文件还请指正。

**Comment by ShadowLyin** [comment]
[tieba ad.zip](https://github.com/neko-dev/neohosts/files/1564483/tieba.ad.zip)
这个是使用hosts后的。
