### ISSUE TITLE
hosts文件中的 :: 是什么意思

### ISSUE THREAD

**Issue by lizhaode** [neoFelhz/neohosts#19]
* 有关此 `issue` 的目的：(请将 `[ ]` 中的空格替换为 `x` 以勾选)
- [ ] 反馈误杀/申请解封（影响到关键服务的正常运行）
- [ ] 申请审查（申请维护者对一个含广告的网站进行分析和数据完善）
- [ ] 提交域名/数据（发现一个广告域名，想提交给 neoHosts）
- [x] 申请技术支持
- [ ] 其它问题

---

* 您要反馈的问题：hosts文件中的 :: 是什么意思

我在hosts文件中看到末尾有这么几行
:: api.map.baidu.com
:: newloc.map.n.shifen.com
:: newvector.map.baidu.com
:: offnavi.map.baidu.com
:: ps.map.baidu.com
:: sv.map.baidu.com
:: ulog.imap.baidu.com

请教这是什么意思

**Comment by neoFelhz** [comment]
IPv6 下的本机 IP。

**Comment by lizhaode** [comment]
@neoFelhz 
那么这些地址为什么要屏蔽IPv6呢？

**Comment by neoFelhz** [comment]
@lizhaode 因为这几个域名涉及到高危的百度精确定位 API，即使在 neoHosts 全面升级 IPv4 IPv6 双栈之前，这几个域名也必须先在 IPv4 IPv6 上都做屏蔽。
