### ISSUE TITLE
淘宝的封杀过多

### ISSUE THREAD

**Issue by bergyu** [neoFelhz/neohosts#20]
* 有关此 `issue` 的目的：(请将 `[ ]` 中的空格替换为 `x` 以勾选)
- [x] 反馈误杀/申请解封（影响到关键服务的正常运行）
- [ ] 申请审查（申请维护者对一个含广告的网站进行分析和数据完善）
- [ ] 提交域名/数据（发现一个广告域名，想提交给 neoHosts）
- [ ] 申请技术支持
- [ ] 其它问题

---

* 您要反馈的问题：

ai.m.taobao.com 和 ai.taobao.com 是爱淘宝的地址，优惠推广的，可以领优惠，不是广告

**Comment by BROBIRD** [comment]
推广也是广告的一种

**Comment by bergyu** [comment]
好吧，我只是觉得这种很多人也会需要的

**Comment by BROBIRD** [comment]
实在要用临时关一下开关不就行了……

**Comment by bergyu** [comment]
其实吧，电脑上基本上都在用插件，手机用这个的更多，手机上操作就没那么方便了，反馈这个的目的其实是不知道还有哪些类似的是被封杀了

**Comment by neoFelhz** [comment]
这是 neoHosts 项目前身 nadhost 的历史遗留数据。
目前我们对淘宝返利跳转推广目前还没有确定态度和处理方式。。
所以，暂时就先保留这个问题吧。
