### ISSUE TITLE
spotify相关规则导致Spotify app中无法加载home页面

### ISSUE THREAD

**Issue by eliversun** [neoFelhz/neohosts#23]
* 有关此 `issue` 的目的：(请将 `[ ]` 中的空格替换为 `x` 以勾选)
- [x] 反馈误杀/申请解封（影响到关键服务的正常运行）
- [ ] 申请审查（申请维护者对一个含广告的网站进行分析和数据完善）
- [ ] 提交域名/数据（发现一个广告域名，想提交给 neoHosts）
- [ ] 申请技术支持
- [ ] 其它问题

---

* 您要反馈的问题：规则中的8条spotify相关规则会导致安卓spotify app 无法加载home页面内容。全部删除spotify相关规则后重启手机即正常。怀疑原因是spclient.wg.spotify.com

**Comment by eliversun** [comment]
对不起，搞错了。跟host没关系，是spotify的问题。

**Comment by eliversun** [comment]
多次重启手机后发现应该是spclient.wg.spotify.com的锅，白名单这个hostname后home页面就能加载出来了，移除白名单重启后立马又加载不出来home页面。

**Comment by metowolf** [comment]
经过测试，规则中的 spclient.wg.spotify.com 会影响移动端的正常使用，感谢反馈

**Comment by metowolf** [comment]
Fixed. https://github.com/neoFelhz/neohosts/commit/c02c6157610710e54cbca86ee9e7ff30abaa13e0
