### ISSUE TITLE
http://www.nmc.cn/ 无法访问

### ISSUE THREAD

**Issue by iiifish** [neoFelhz/neohosts#24]
* 有关此 `issue` 的目的：(请将 `[ ]` 中的空格替换为 `x` 以勾选)
- [x] 反馈误杀/申请解封（影响到关键服务的正常运行）
- [ ] 申请审查（申请维护者对一个含广告的网站进行分析和数据完善）
- [ ] 提交域名/数据（发现一个广告域名，想提交给 neoHosts）
- [ ] 申请技术支持
- [ ] 其它问题

---

* 您要反馈的问题：http://www.nmc.cn/ 无法访问

【已解决】大概是另外个软件没卸载干净

**Comment by metowolf** [comment]
测试仅发现拦截以下域名，访问正常
 - w.cnzz.com // 统计服务

请提供更多信息，如控制台报错、抓包信息等
