### ISSUE TITLE
_data/basic/adwo.txt 的 “r3 adwo.com ”

### ISSUE THREAD

**Issue by limard** [neoFelhz/neohosts#38]
* 有关此 `issue` 的目的：(请将 `[ ]` 替换为 `[x]` 以勾选)
- [ ] 反馈误杀/申请解封（影响到关键服务的正常运行）
- [ ] 申请审查（申请维护者对一个含广告的网站进行分析和数据完善）
- [ ] 提交域名/数据（发现一个广告域名，想提交给 neoHosts）
- [ ] 申请技术支持
- [X] 其它问题

---

* 您要反馈的问题：

_data/basic/adwo.txt的最后一行
0.0.0.0 r3 adwo.com 
是不是应该是 0.0.0.0 r3.adwo.com ???
少了个点

**Comment by duangsuse** [comment]
这样简单的修改的话，不妨直接 __fork__，修复并开一个 [Pull Request](https://github.com/neoFelhz/neohosts/pulls)，可以帮助维护者节省时间来解决更重要的问题 :smiley:

**Comment by limard** [comment]
好。。。我也是偷懒了。。
