### ISSUE TITLE
广告域名及奇虎相关域名

### ISSUE THREAD

**Issue by hfzgvxldnmvs** [neoFelhz/neohosts#41]
* 有关此 `issue` 的目的：(请将 `[ ]` 替换为 `[x]` 以勾选)
- [ ] 反馈误杀/申请解封（影响到关键服务的正常运行）
- [ ] 申请审查（申请维护者对一个含广告的网站进行分析和数据完善）
- [x] 提交域名/数据（发现一个广告域名，想提交给 neoHosts）
- [ ] 申请技术支持
- [ ] 其它问题

---

* 您要反馈的问题：
点击了网站中想要打开的新网页后，原网页会被跳转成广告页面，
http://p2.hyz86.com/AD/Default.aspx?id=5927
在其他某些网站也会看到该地址
例如
http://jiyingw.com/26757.html
http://www.runningmanfen.com/rmdownload/runningman2018/

以下看来是奇虎的东西，不知道有什么作用。希望屏蔽掉更好
http://js.passport.qihucdn.com/11.0.1.js?a68fcba45d115c2ffe65883c277eb5b1
http://s7.qhres.com/static/ab77b6ea7f3fbf79.js
https://jspassport.ssl.qhimg.com/11.0.1.js

不知道是网站自己加的，还是因为没加https被劫持插入的。

**Comment by metowolf** [comment]
感谢提交。
该类域名为 360 搜索站长平台的自动收录使用，这里不作屏蔽处理。
关于广告页面的跳转，这里没有成功重现，怀疑是运营商劫持 HTTP 请求导致的。
