### ISSUE TITLE
误杀 mobile.qzone.qq.com

### ISSUE THREAD

**Issue by Skimige** [neoFelhz/neohosts#42]
* 有关此 `issue` 的目的：
- [x] 反馈误杀/申请解封（影响到关键服务的正常运行）
- [ ] 申请审查（申请维护者对一个含广告的网站进行分析和数据完善）
- [ ] 提交域名/数据（发现一个广告域名，想提交给 neoHosts）
- [ ] 申请技术支持
- [ ] 其它问题

---

* 您要反馈的问题：
http://mobile.qzone.qq.com/l?g=279&_wv=1&i=c159e493bb5d645bd7e80700&u=2481215937&a=311&sg=84
QQ 空间分享（到 QQ/TIM/etc.）涉及到此域名。

**Comment by metowolf** [comment]
经确认，该域名为 QQ 空间手机版部分组件使用，属于过度拦截，已去除。
感谢反馈~
