### ISSUE TITLE
网易云音乐网页版相关域名解封

### ISSUE THREAD

**Issue by love4taylor** [neoFelhz/neohosts#43]
* 有关此 `issue` 的目的：(请将 `[ ]` 替换为 `[x]` 以勾选)
- [x] 反馈误杀/申请解封（影响到关键服务的正常运行）
- [ ] 申请审查（申请维护者对一个含广告的网站进行分析和数据完善）
- [ ] 提交域名/数据（发现一个广告域名，想提交给 neoHosts）
- [ ] 申请技术支持
- [ ] 其它问题

---

* 您要反馈的问题：
https://acstatic-dun.126.net/tool.min.js
如果这个 js 无法被加载, 网页端网易云音乐将无法登录帐号,点击登录无网络请求, 解封后恢复.

**Comment by metowolf** [comment]
经过调查，acstatic-dun.126.net 为网易易盾云安全 sdk 使用域名，属于误杀已解封。
感谢反馈~
