### ISSUE TITLE
文档问题

### ISSUE THREAD

**Issue by Xeonacid** [neoFelhz/neohosts#44]
* 有关此 `issue` 的目的：(请将 `[ ]` 替换为 `[x]` 以勾选)
- [ ] 反馈误杀/申请解封（影响到关键服务的正常运行）
- [ ] 申请审查（申请维护者对一个含广告的网站进行分析和数据完善）
- [ ] 提交域名/数据（发现一个广告域名，想提交给 neoHosts）
- [ ] 申请技术支持
- [x] 其它问题

---

* 您要反馈的问题：
文档中[Hosts 生效](https://hosts.nfz.moe/#/./make-hosts-active?id=chrome-%E6%B5%8F%E8%A7%88%E5%99%A8)一节对于Chrome的指引为访问`chrome://dns/`，本机Chrome测试无此地址，访问错误`ERR_INVALID_URL`
应当更改为`chrome://net-internals/#dns`
本机Chrome版本：70.0.3514.0

**Comment by metowolf** [comment]
感谢提醒，已做修改
