### ISSUE TITLE
hosts无法下载，何不在github上托管一份？

### ISSUE THREAD

**Issue by horizonl** [neoFelhz/neohosts#46]
* 有关此 `issue` 的目的：(请将 `[ ]` 替换为 `[x]` 以勾选)
- [ ] 反馈误杀/申请解封（影响到关键服务的正常运行）
- [ ] 申请审查（申请维护者对一个含广告的网站进行分析和数据完善）
- [ ] 提交域名/数据（发现一个广告域名，想提交给 neoHosts）
- [ ] 申请技术支持
- [x] 其它问题

---

* 您要反馈的问题：合肥电信，无法解析到hosts.neo.moe以至无法下载hosts。
* 既然在github上，何不和[其他hosts项目](https://github.com/googlehosts/hosts) 一样直接在github托管一份？

**Comment by duangsuse** [comment]
https://github.com/neoFelhz/neohosts/tree/gh-pages/full

其实本来就是托管在了 GitHub 上，不过使用了自定义域名
你可以到这里来下载 Hosts

**Comment by duangsuse** [comment]
另外，域名好像搞错了，不是 hosts.neo.moe，应该到 https://hosts.nfz.moe/ 下载 :smiley:

**Comment by metowolf** [comment]
https://raw.githubusercontent.com/neoFelhz/neohosts/gh-pages/basic/hosts
是有托管在 github 上的，切换分支可见 😄

**Comment by neoFelhz** [comment]
https://hosts.nfz.moe 已经恢复解析
