### ISSUE TITLE
屏蔽国产app启动广告

### ISSUE THREAD

**Issue by scriptxyz** [neoFelhz/neohosts#47]
友盟主要使用了如下的域名

g1.tagtic.cn 	
img.adnyg.com 	
img.adnyg.com.w.kunlungr.com 	
log.tagtic.cn 	
pgdt.ugdtimg.com 	
sdownload.stargame.com 	
ulogs.umeng.com

**Comment by wulei-student** [comment]
ulogs.umeng.com这个是友盟的，其他的应该不是，是其它公司的。pgdt.ugdtimg.com是腾讯的域名。
