### ISSUE TITLE
 adnxs.com 是一个误导性的网站

### ISSUE THREAD

**Issue by hfzgvxldnmvs** [neoFelhz/neohosts#50]
* 有关此 `issue` 的目的：(请将 `[ ]` 替换为 `[x]` 以勾选)
- [ ] 反馈误杀/申请解封（影响到关键服务的正常运行）
- [ ] 申请审查（申请维护者对一个含广告的网站进行分析和数据完善）
- [x] 提交域名/数据（发现一个广告域名，想提交给 neoHosts）
- [ ] 申请技术支持
- [ ] 其它问题

---

* 您要反馈的问题：
广告域名:adnxs.com

新闻来源:https://malwaretips.com/blogs/ib-adnxs-popup-virus/
http://wubingdu.cn/ib-adnxs-com/

**Comment by neoFelhz** [comment]
https://github.com/neoFelhz/neohosts/blob/data/_data/basic/common.txt#L408
 Already added long ago.
