### ISSUE TITLE
腾讯视频 误杀

### ISSUE THREAD

**Issue by honwen** [neoFelhz/neohosts#61]
* 有关此 `issue` 的目的：(请将 `[ ]` 替换为 `[x]` 以勾选)
- [x] 反馈误杀/申请解封（影响到关键服务的正常运行）
- [ ] 申请审查（申请维护者对一个含广告的网站进行分析和数据完善）
- [ ] 提交域名/数据（发现一个广告域名，想提交给 neoHosts）
- [ ] 申请技术支持
- [ ] 其它问题

---

* 您要反馈的问题：

https://github.com/neoFelhz/neohosts/blob/904af304e6e6a3d5187893d919a0ffddde37eb4e/_data/basic/qq.txt#L40

https://github.com/neoFelhz/neohosts/blob/904af304e6e6a3d5187893d919a0ffddde37eb4e/_data/basic/qq.txt#L130

实测去掉就可以正常播放

**Comment by honwen** [comment]
![snipaste_2019-01-06_16-40-34](https://user-images.githubusercontent.com/12322033/50733962-d02da480-11d1-11e9-9685-82f17d6d3211.png)

从其他规则来看, 这一行误杀范围太广

**Comment by metowolf** [comment]
感谢反馈，经过验证已经移除该规则。
