### ISSUE TITLE
Full hosts 中出现错误数据

### ISSUE THREAD

**Issue by iKirby** [neoFelhz/neohosts#62]
* 有关此 `issue` 的目的：(请将 `[ ]` 替换为 `[x]` 以勾选)
- [ ] 反馈误杀/申请解封（影响到关键服务的正常运行）
- [ ] 申请审查（申请维护者对一个含广告的网站进行分析和数据完善）
- [ ] 提交域名/数据（发现一个广告域名，想提交给 neoHosts）
- [ ] 申请技术支持
- [x] 其它问题

---

* 您要反馈的问题：

版本 20190106100438 ，第 4935 和 4936 行数据不正确：

```
eTV0.0.0.0 api.push.le.com
eTV:: api.push.le.com
```

**Comment by metowolf** [comment]
感谢反馈，已经定位并修复
