### ISSUE TITLE
网站https://hosts.nfz.moe/直接打不开

### ISSUE THREAD

**Issue by Accelerator086** [neoFelhz/neohosts#67]
* 有关此 `issue` 的目的：(请将 `[ ]` 替换为 `[x]` 以勾选)
- [ ] 反馈误杀/申请解封（影响到关键服务的正常运行）
- [ ] 申请审查（申请维护者对一个含广告的网站进行分析和数据完善）
- [ ] 提交域名/数据（发现一个广告域名，想提交给 neoHosts）
- [ ] 申请技术支持
- [ ] 其它问题

---

* 您要反馈的问题：

网站https://hosts.nfz.moe/直接打不开
![image](https://user-images.githubusercontent.com/32789300/55344646-742ca080-54e0-11e9-9e8b-0ea089663fed.png)

**Comment by v3aqb** [comment]
证书过期。。。

**Comment by ookangzheng** [comment]
管理員還在放假嗎 :D

**Comment by ookangzheng** [comment]
聲明: 版權所有權屬於 [neoHosts](https://github.com/neoFelhz/neohosts)

**這只是暫時性的mirror**
我把hsts關閉，即可進入，今天下載和更新。 2019-04-07 GMT+8
https://github.com/ookangzheng/some-mirros

**Comment by metowolf** [comment]
目前可以先使用 https://cdn.jsdelivr.net/gh/neoFelhz/neohosts@gh-pages/
README 中的链接已经修正

**Comment by hizjz** [comment]
仍然不行
