### ISSUE TITLE
使用jsDelivr是否存在cdn缓存不能及时刷新的问题？

### ISSUE THREAD

**Issue by josark2005** [neoFelhz/neohosts#73]
* 有关此 `issue` 的目的：(请将 `[ ]` 替换为 `[x]` 以勾选)
- [ ] 反馈误杀/申请解封（影响到关键服务的正常运行）
- [ ] 申请审查（申请维护者对一个含广告的网站进行分析和数据完善）
- [ ] 提交域名/数据（发现一个广告域名，想提交给 neoHosts）
- [ ] 申请技术支持
- [x] 其它问题

---

* 您要反馈的问题：

使用jsDelivr是否存在cdn缓存不能及时刷新的问题？

**Comment by neoFelhz** [comment]
jsDelivr 默认缓存 7 天，不算什么很严重的问题。
