### ISSUE TITLE
京东网页版无法登录

### ISSUE THREAD

**Issue by yEs1do** [neoFelhz/neohosts#8]
屏蔽 wq.jd.com 导致京东网页版无法进行登录，是否考虑解除屏蔽？

嘛，虽然我是手动修改的 host 文件解决啦

**Comment by duangsuse** [comment]
🌚  @neoFelhz  考虑把这个分到 __extra/jd__ 去吧, 多为不同需求的人考虑一下

**Comment by duangsuse** [comment]
(虽然我觉得直接写个自助选择屏蔽的js更好

**Comment by neoFelhz** [comment]
能提供一下京东登陆页面的控制台 console 输出么？因为这个域名属于 QQ 广告的一部分。

**Comment by yEs1do** [comment]
@neoFelhz 不会弄呢😶要不你亲自登录一下试试吧😅

**Comment by neoFelhz** [comment]
没有 console log 我没法确认这个域名加载的文件是登陆时所必要的。这个 issue 予以保留，得到 console log 后域名予以移除。

**Comment by neoFelhz** [comment]
![](https://user-images.githubusercontent.com/19367350/32133404-bb658316-bc09-11e7-87e1-63b594f0fe7b.PNG)
![](https://user-images.githubusercontent.com/19367350/32133414-de6818c4-bc09-11e7-903e-16cd7f8f68a0.PNG)

无论是 京东电脑版网页 还是 京东手机版网页，在使用 Dev Tools 对 `wq.jd.com` 域名进行 Block 以后页面均未报错、可正常登陆；也没有任何证据表明京东的登录页面引用了来自 `wq.jd.com` 的资源。故不予移除。

**Comment by neoFelhz** [comment]
`wq.jd.com` 经确认为京东 H5 页面，数据中将会移除该域名。
请在十分钟后更新 Hosts，并通过开关飞行模式、重启等方式使 Hosts 生效即可恢复正常。
