### ISSUE TITLE
引用了贵项目，专门来给你们点赞的

### ISSUE THREAD

**Issue by gentlyxu** [neoFelhz/neohosts#80]
* 有关此 `issue` 的目的：(请将 `[ ]` 替换为 `[x]` 以勾选)
- [ ] 反馈误杀/申请解封（影响到关键服务的正常运行）
- [ ] 申请审查（申请维护者对一个含广告的网站进行分析和数据完善）
- [ ] 提交域名/数据（发现一个广告域名，想提交给 neoHosts）
- [ ] 申请技术支持
- [x] 其它问题

---

* 您要反馈的问题：我引用了贵项目，进行整合转换，以及剔除已经失效的域名，生成了支持dnsmasq和adguardHome格式的新列表，我和你们的目标一致，保护隐私，屏蔽广告。目前我这个项目主要是自己使用。但完全开源，在此向你们表示感谢。我的项目地址是：https://github.com/privacy-protection-tools/anti-AD

**Comment by neoFelhz** [comment]
也为 anti-AD 项目送上 star~

**Comment by gentlyxu** [comment]
谢谢鼓励！
