### ISSUE TITLE
用rsc文件倒入mikrotik里的固定dns地址要怎样才能删除

### ISSUE THREAD

**Issue by noobsora** [neoFelhz/neohosts#85]
- [x] 申请技术支持

---

* 您要反馈的问题：
您好，请问用rsc文件倒入mikrotik里的固定dns地址要怎样才能删除？

**Comment by wy16W2pIilK1xgqN** [comment]
先手动删除吧，估计楼主没有做过多的设置，手动删很容易。

以后的脚本，在第一行 添加 
 ip dns static remove [find comment =neoHosts]
之后每一行行尾i添加  comment =neoHosts
大概结果是这样的。
```
 ip dns static remove [find comment =neoHosts]
ip dns static add address=127.0.0.1 name=001.0x1f4b0.com    comment=neoHosts
ip dns static add address=127.0.0.1 name=002.0x1f4b0.com   comment=neoHosts
ip dns static add address=127.0.0.1 name=003.0x1f4b0.com    comment=neoHosts
ip dns static add address=127.0.0.1 name=004.0x1f4b0.com   comment=neoHosts
ip dns static add address=127.0.0.1 name=005.0x1f4b0.com   comment=neoHosts
ip dns static add address=127.0.0.1 name=006.0x1f4b0.com   comment=neoHosts
```
多说一句 这属于 RouterOS 基本操作。
楼主因该去 RouterOS   群去问。

建议关闭该问题。

**Comment by noobsora** [comment]
> 先手动删除吧，估计楼主没有做过多的设置，手动删很容易。
> 
> 以后的脚本，在第一行 添加
> ip dns static remove [find comment =neoHosts]
> 之后每一行行尾i添加 comment =neoHosts
> 大概结果是这样的。
> 
> ```
>  ip dns static remove [find comment =neoHosts]
> ip dns static add address=127.0.0.1 name=001.0x1f4b0.com    comment=neoHosts
> ip dns static add address=127.0.0.1 name=002.0x1f4b0.com   comment=neoHosts
> ip dns static add address=127.0.0.1 name=003.0x1f4b0.com    comment=neoHosts
> ip dns static add address=127.0.0.1 name=004.0x1f4b0.com   comment=neoHosts
> ip dns static add address=127.0.0.1 name=005.0x1f4b0.com   comment=neoHosts
> ip dns static add address=127.0.0.1 name=006.0x1f4b0.com   comment=neoHosts
> ```
> 
> 多说一句 这属于 RouterOS 基本操作。
> 楼主因该去 RouterOS 群去问。
> 
> 建议关闭该问题。

非常感谢！
