### ISSUE TITLE
@ in URL

### ISSUE THREAD

**Issue by p1r473** [neoFelhz/neohosts#91]
Hello,
I cant use the following URLs in my script due to them having '@'
Can you remove '@' from URL?

https://cdn.jsdelivr.net/gh/neoFelhz/neohosts@gh-pages/basic/hosts
https://cdn.jsdelivr.net/gh/neoFelhz/neohosts@gh-pages/full/hosts

**Comment by Jkkoi** [comment]
https://raw.githubusercontent.com/neoFelhz/neohosts/gh-pages/basic/hosts
https://raw.githubusercontent.com/neoFelhz/neohosts/gh-pages/full/hosts

**Comment by p1r473** [comment]
Thanks!
